[package]
name = "baldrdash"
version = "0.1.0"
authors = ["The Spidermonkey and Cranelift developers"]

[lib]
crate-type = ["rlib"]
name = "baldrdash"

[dependencies]
cranelift-codegen = "0.20.0"
cranelift-wasm = "0.20.1"
target-lexicon = "0.0.3"
log = { version = "0.4.4", default-features = false, features = ["release_max_level_warn"] }
env_logger = "0.5.6"

[build-dependencies]
bindgen = {version = "0.39", default-features = false} # disable `logging` to reduce code size

# Uncomment this to enable perf support in release mode.
#[profile.release]
#debug = true
